Contact form implimentation
RWUBAKWANAYO/Portfolio-Setup pull request #3
Opened 2022-03-22 20:52 UTC by RWUBAKWANAYO

# In this project we: 

- Add contact section in HTML file
- Add styles to created section
- Invite learning partner to contribute to this project
- setup mobile version of new section
- Fix linter errors in the project

2022-03-22 22:02 UTC, brytebee requested changes
Hi Team 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- amazing design✔️
- no linter errors✔️
- no console errors✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] **Optional:** Kindly update the live demo link on your readme. It is broken.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 22:02 UTC, brytebee commented on index.html
> +      <input type="submit" value="Get It Touch" id="contact-submit" />
- [ ] **Required:** You have done an amazing job 👏 . However, it is required that your button is interactive.

![image](https://user-images.githubusercontent.com/27709832/159583229-9c6b7f9d-233c-438e-a513-8252f2f643fd.png)

2022-03-23 00:33 UTC, mateo951 approved these changes
### Hi @RWUBAKWANAYO, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 💪😎 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 00:33 UTC, mateo951 commented on index.html
> +      <input type="submit" value="Get It Touch" id="contact-submit" />
Addressed ✔

2022-03-24 07:11 UTC, merged